#!/usr/bin/env python3
"""Install the MCP parameter probe for Claude Code and OpenCode on WSL/Linux."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

SERVER_NAME = "auditcov-parameter-probe"
INSTALL_MARKER = "Generated by AuditCov MCP parameter probe installer."


def data_home() -> Path:
    configured = os.environ.get("XDG_DATA_HOME")
    return Path(configured).expanduser() if configured else Path.home() / ".local" / "share"


def state_home() -> Path:
    configured = os.environ.get("XDG_STATE_HOME")
    return Path(configured).expanduser() if configured else Path.home() / ".local" / "state"


def config_home() -> Path:
    configured = os.environ.get("XDG_CONFIG_HOME")
    return Path(configured).expanduser() if configured else Path.home() / ".config"


def install_paths() -> dict[str, Path]:
    install_dir = data_home() / "auditcov-mcp-probe"
    return {
        "install_dir": install_dir,
        "server": install_dir / "mcp_parameter_probe.py",
        "log": state_home() / "auditcov-mcp-probe" / "events.jsonl",
        "opencode_plugin": config_home()
        / "opencode"
        / "plugins"
        / "auditcov_mcp_parameter_probe.ts",
    }


def source_server_path() -> Path:
    return Path(__file__).resolve().parent.parent / "tools" / "mcp_parameter_probe.py"


def claude_config(server_path: Path, log_path: Path) -> dict[str, object]:
    return {
        "type": "stdio",
        "command": "python3",
        "args": [str(server_path)],
        "env": {
            "MCP_PROBE_CLIENT": "claude-code",
            "MCP_PROBE_LOG": str(log_path),
        },
    }


def render_opencode_plugin(server_path: Path, log_path: Path) -> str:
    command = ["python3", str(server_path)]
    environment = {
        "MCP_PROBE_CLIENT": "opencode",
        "MCP_PROBE_LOG": str(log_path),
    }
    return f"""// {INSTALL_MARKER}
export const AuditCovMcpParameterProbe = async () => {{
  return {{
    config: async (config) => {{
      config.mcp ??= {{}}
      config.mcp[{json.dumps(SERVER_NAME)}] = {{
        type: "local",
        command: {json.dumps(command)},
        environment: {json.dumps(environment)},
        enabled: true,
      }}
    }},
  }}
}}
"""


def run(command: list[str], *, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, check=check, text=True, capture_output=True)


def ensure_executable(name: str) -> None:
    if shutil.which(name) is None:
        raise RuntimeError(f"required executable is not available in PATH: {name}")


def install(force: bool) -> None:
    ensure_executable("python3")
    ensure_executable("claude")
    ensure_executable("opencode")

    paths = install_paths()
    source = source_server_path()
    if not source.is_file():
        raise RuntimeError(f"probe server source is missing: {source}")

    plugin_path = paths["opencode_plugin"]
    if plugin_path.exists():
        existing = plugin_path.read_text(encoding="utf-8", errors="replace")
        if INSTALL_MARKER not in existing:
            raise RuntimeError(f"refusing to overwrite unrelated file: {plugin_path}")
        if not force:
            raise RuntimeError("probe is already installed; rerun with --force to refresh it")

    paths["install_dir"].mkdir(parents=True, exist_ok=True)
    paths["log"].parent.mkdir(parents=True, exist_ok=True)
    plugin_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, paths["server"])
    paths["server"].chmod(0o755)
    plugin_path.write_text(
        render_opencode_plugin(paths["server"], paths["log"]), encoding="utf-8"
    )

    if force:
        run(["claude", "mcp", "remove", SERVER_NAME, "--scope", "user"], check=False)

    config_json = json.dumps(claude_config(paths["server"], paths["log"]), separators=(",", ":"))
    result = run(
        ["claude", "mcp", "add-json", SERVER_NAME, config_json, "--scope", "user"],
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            "Claude Code registration failed. OpenCode files were installed, but Claude "
            f"was not configured. stderr: {result.stderr.strip() or result.stdout.strip()}"
        )

    print("MCP parameter probe installed for Claude Code and OpenCode.")
    print(f"Server name: {SERVER_NAME}")
    print(f"Log file:    {paths['log']}")
    print("Restart both clients before testing.")


def uninstall() -> None:
    paths = install_paths()
    plugin_path = paths["opencode_plugin"]
    if plugin_path.is_file():
        existing = plugin_path.read_text(encoding="utf-8", errors="replace")
        if INSTALL_MARKER not in existing:
            raise RuntimeError(f"refusing to remove unrelated file: {plugin_path}")
        plugin_path.unlink()

    if shutil.which("claude"):
        run(["claude", "mcp", "remove", SERVER_NAME, "--scope", "user"], check=False)

    server_path = paths["server"]
    if server_path.is_file():
        server_path.unlink()

    print("Probe registrations removed. The log file was intentionally preserved:")
    print(paths["log"])


def status() -> None:
    paths = install_paths()
    print(f"Server file:      {paths['server']} ({'present' if paths['server'].is_file() else 'missing'})")
    print(
        f"OpenCode plugin:  {paths['opencode_plugin']} "
        f"({'present' if paths['opencode_plugin'].is_file() else 'missing'})"
    )
    print(f"Log file:         {paths['log']} ({'present' if paths['log'].is_file() else 'not created yet'})")
    if shutil.which("claude"):
        result = run(["claude", "mcp", "get", SERVER_NAME], check=False)
        text = result.stdout.strip() or result.stderr.strip()
        print(f"Claude Code:      {text or 'no status returned'}")
    else:
        print("Claude Code:      executable not found")
    if shutil.which("opencode"):
        result = run(["opencode", "mcp", "list"], check=False)
        text = result.stdout.strip() or result.stderr.strip()
        print(f"OpenCode MCP list:\n{text or 'no status returned'}")
    else:
        print("OpenCode:         executable not found")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("install", "uninstall", "status"), nargs="?", default="install")
    parser.add_argument("--force", action="store_true", help="Refresh files and replace the Claude user registration.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    try:
        if args.action == "install":
            install(args.force)
        elif args.action == "uninstall":
            uninstall()
        else:
            status()
    except (OSError, RuntimeError, subprocess.SubprocessError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc


if __name__ == "__main__":
    main()
